name: Build

on: [push]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    #container: ubuntu:latest
    
    #services:
    #  postgres:
    #    image: postgres  
    #    ports: 
    #      - 5432:5432
    #  tomcat:
    #    image: tomcat
    #    ports:
    #      - 8080:8080    
        
    env:
      BUILD: db
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgrespass
      POSTGRES_DATABASE: 
      
    steps: 
    
      - name: Pull Repo
        uses: actions/checkout@v1
      
      - name: Run Docker Compose Up
        run: |
          docker-compose up -d
        
      - name: Run Docker Compose test
        run: |
          docker-compose exec -T pg-test sh -c "echo 'PG BOX'"
          docker-compose exec -T tc-test sh -c "echo 'TC BOX'"
          docker-compose exec -T pg-test sh -c "psql -U dab -c 'select * from test;'" 
          docker-compose exec -T tc-test sh -c "/usr/local/tomcat/bin/version.sh"
      #- name: Checkout
      #  uses: actions/checkout@v1
        
      #- name: Install
      #  run: |
      #    apt-get install -y postgresql
          
      #- name: Build
      #  run: docker run --rm --name pgab -d -p 5432:5432
      #  env: 
      #    POSTGRES_PASSWORD: docker
          
          
      #- name: SetupDatabase
      #  run: |
      #    docker-compose exec -T pg-test sh -c "createdb -U postgres dab"
      #    docker-compose exec -T pg-test sh -c "createuser -U postgres dab"
      #    docker-compose exec -T pg-test sh -c "psql -d dab -U dab -c 'create table test (i int, d varchar);'"
      #    docker-compose exec -T pg-test sh -c "psql -d dab -U dab -c 'insert into test values (100, \'abc\');'"
          
      #- name: Check Database Init
      #  run: docker-compose exec -T pg-test sh -c "psql -d dab -c 'select * from test;'" 
   
   