name: Build

on: [push]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    container: node:10.19-jessie

    services:
      postgres:
        image: postgres      
        
    env:
      BUILD: db
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgrespass
      
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
        
      #- name: Install
      #  run: |
      #    apt-get install -y postgresql
          
      - name: Build
        run: docker run --rm --name pgab -d -p 5432:5432
        env: 
          POSTGRES_PASSWORD: docker
          
          
      - name: SetupPG
        run: |
          psql -d postgres -U postgres createdb dab
          psql -d postgres -U postgres createuser dab
          psql -d dab -U dab -c 'create table test (i int, d varchar);'
          psql -d dab -U dab -c 'insert into test values (100, \'abc\');'
          
      - name: CheckPG
        run: psql -d dab -c 'select * from test;' 
   
   