name: Build

on: [push]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    container: node:10.19-jessie


    services:

      postgres:
        image: postgres      
        ports:
        - 5432:5432
        
      tomcat:
        image: tomcat 
        
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
          
      - name: Build
        run: |
          psql -d postgres -c 'select 1;'
          psql -d postgres createdb dab
          psql -d dab createuser dab
          psql -d dab -c 'create table test (i int, d varchar);'
          psql -d dab -c 'insert into test values (100, "abc");'    
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          
      - name: Check PG
        run: psql -d dab -c 'select * from test;' 
          
      - name: Deploy
        run: |
          mv gradle.ga.properties gradle.properties
          gradle deploy
   
   