name: Build

on: [push]

jobs:

  container-job:
  
    runs-on: ubuntu-latest

    #container: ubuntu:latest
    
    #services:
    #  postgres:
    #    image: postgres  
    #    ports: 
    #      - 5432:5432
    #  tomcat:
    #    image: tomcat
    #    ports:
    #      - 8080:8080    
        
    env:
      BUILD: db
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgrespass
      
    steps: 
    
      - name: Pull Repo
        uses: actions/checkout@v1
      
      - name: Run Docker Compose Up
        run: |
          docker-compose up -d
        
      - name: Install Required Python Modules
        run: |
          docker-compose exec -T pg-test sh -c "echo 'PG BOX'"
        
      #- name: Checkout
      #  uses: actions/checkout@v1
        
      #- name: Install
      #  run: |
      #    apt-get install -y postgresql
          
      #- name: Build
      #  run: docker run --rm --name pgab -d -p 5432:5432
      #  env: 
      #    POSTGRES_PASSWORD: docker
          
          
      - name: SetupDatabase
        run: |
          docker -v
          docker exec -it postgres /bin/sh
          docker exec -it postgres echo 'echoing'
          docker exec -it postgres psql -d postgres -U postgres createdb dab
          docker exec -it postgres psql -d postgres -U postgres createdb dab
          docker exec -it postgres psql -d postgres -U postgres createuser dab
          docker exec -it postgres psql -d dab -U dab -c 'create table test (i int, d varchar);'
          docker exec -it postgres psql -d dab -U dab -c 'insert into test values (100, \'abc\');'
          
      - name: CheckPG
        run: psql -d dab -c 'select * from test;' 
   
   