name: Build

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
  
      - uses: actions/checkout@v1
      
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Build with Gradle
        run: |
          mv gradle.ga.properties gradle.properties
          cat build.gradle | sed 's/nz.govt.linz/org.apache.tomcat/' > build.gradle
          gradle war 
      

  
#  deploy:
#    runs-on: ubuntu-latest
#      
#    steps:
#      - name: Test deploy to TC7
#        uses: docker://alpine:3.8
   
   